site_name: OVPrecision Data Upload
theme:
  name: mkdocs
nav:
  - Home: index.md
  - md5sums: md5sums.md
  - WSL: wsl.md 
extra_css:
  - assets/css/styles.css
site_url: https://ikeller.github.io/ovp_user_docs/
use_directory_urls: false

